# Generated by Django 3.2.8 on 2021-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
