# Generated by Django 3.2.8 on 2021-10-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
    ]
