# Generated by Django 3.2.8 on 2021-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_remove_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
